Repository k1LoW/deck, pull requests merged in 2025-08, with the labels that each got.

#325 fix: correct profile name validation
  deck.go
  deck_test.go
Labels: bug

#326 feat: support config.yml for global setting
  README.md
  cmd/apply.go
  config/config.go
  md/md.go
  md/md_test.go
Labels: enhancement, minor

#340 fix: adjust configuration and data file placement rules
  README.md
  config/config.go
Labels: bug, minor, breaking change

#346 feat: support debug level logging with -vv option
  cmd/apply.go
Labels: minor

#349 fix: correct `ignore` handing
  cmd/apply.go
  md/md.go
  testdata/ignore.md
Labels: bug

#356 fix: to work properly with Shared Drive
  deck.go
  preload.go
Labels: bug

#355 ci: introduce integration test on GitHub Actions
  .github/workflows/integration.yml
  .gitignore
  helper_test.go
  integration_test.go
Labels: integration-test

#378 fix: correct handling of `ignore` outside in non-watch mode.
  cmd/apply.go
Labels: bug

#382 feat: support Backslash escapes
  md/md.go
  testdata/br.md
  testdata/br.md-1.golden.png
  testdata/br.md.golden
Labels: enhancement, minor

#394 feat: reuse blockquote block if possible
  apply.go
Labels: enhancement

#402 fix: If a line contains only a single `<br>`, it will not be broken and will be escaped.
  md/md.go
  testdata/br.md
  testdata/br.md-1.golden.png
  testdata/br.md.golden
Labels: bug, integration-test

#409 feat: add --base flag to new subcommand
  cmd/new.go
Labels: enhancement

#414 feat: support image link
  action.go
  apply.go
  compare.go
  convert.go
  md/md.go
  md/md_test.go
  preload.go
  slide.go
  testdata/images.md
  testdata/images.md-4.golden.png
  testdata/images.md.golden
Labels: enhancement, minor
