Repository k1LoW/deck, pull requests merged in 2025-06, with the labels that each got.

#111 feat(deck): handle single-item bullet lists correctly
  deck.go
  integration_test.go
  testdata/single_list.md
Labels: bug

#112 fix: improve update logic for slides
  Makefile
  deck.go
  diff.go
  diff_test.go
  integration_test.go
  md/md.go
  testdata/cap.md
  testdata/cap.md.golden
  testdata/empty_link.md.golden
  testdata/empty_list.md.golden
  testdata/list_and_paragraph.md
  testdata/list_and_paragraph.md.golden
  testdata/paragraph_and_list.md.golden
  testdata/slide.md
  testdata/slide.md.golden
Labels: enhancement, minor, breaking change

#114 fix: improve file change detection for vim compatibility
  cmd/apply.go
Labels: enhancement, minor

#121 fix: improve action generation and similarity scoring
  Makefile
  action.go
  action_test.go
  deck_test.go
  similarity_test.go
Labels: bug

#126 feat(md): support image
  deck.go
  img/logo.gif
  img/logo.jpg
  md/md.go
  md/md_test.go
  slide.go
  testdata/image.md
  testdata/image.md.golden
Labels: enhancement, minor

#128 Support image ( `![img](path/to/image.png)` )
  README.md
  action.go
  deck.go
  go.mod
  go.sum
  img/logo.gif
  img/logo.jpg
  integration_test.go
  md/md.go
  md/md_test.go
  similarity_test.go
  slide.go
  slide_test.go
  testdata/image.md
  testdata/image.md.golden
  testdata/images.md
  testdata/images.md.golden
  testdata/test.compressed.jpeg
Labels: enhancement, minor

#129 feat(md): add support for code blocks in slide content
  md/md.go
  md/md_test.go
  testdata/codeblock.md
  testdata/codeblock.md.golden
Labels: enhancement, minor

#133 feat: add support for converting code blocks to images
  cmd/apply.go
  go.mod
  go.sum
  integration_test.go
  md/md.go
  slide.go
  slide_test.go
Labels: enhancement, minor

#139 feat(deck): add functionality to copy images between (create/delete) slides when update
  deck.go
Labels: enhancement

#144 fix(md): rename `value` to `content` in code block
  README.md
  md/md.go
  testdata/codeblock.md.golden
Labels: minor, breaking change

#147 feat: support bullet in shape
  deck.go
Labels: enhancement, minor

#150 fix(deck): rename methods and add logging for page operations
  deck.go
  handler/dot/dot.go
  integration_action_test.go
Labels: breaking change

#151 feat(dot): display a spinner when retrying a Google Slides API call
  cmd/apply.go
  deck.go
  go.mod
  go.sum
  handler/dot/dot.go
Labels: enhancement, minor

#152 fix: rename package
  cmd/apply.go
  logger/dot/dot.go
Labels: breaking change

#154 feat(logger): enhance dot handler for deleted/moved pages
  logger/dot/dot.go
Labels: enhancement

#157 fix: cache calculated checksums and pHash values for image comparison
  action.go
  slide.go
Labels: enhancement

#159 fix(md): correct image copying logic in ToSlides
  md/md.go
Labels: bug

#164 fix: respond when images are manually deleted in Google Slides
  deck.go
Labels: bug

#165 fix: prune old images via markdown
  action.go
  action_test.go
  deck.go
  integration_test.go
  md/md.go
  slide.go
  slide_test.go
  testdata/images.md.golden
Labels: enhancement, minor

#170 feat(apply): switch to JSON logging when `--verbose` and enhance action details structure
  cmd/apply.go
  deck.go
Labels: breaking change

#172 feat: create error.json if deck fails
  action.go
  cmd/root.go
  config/config.go
  deck.go
  go.mod
  go.sum
  logger/dot/dot.go
  md/md.go
  slide.go
Labels: enhancement, minor

#174 feat: integrate tail-based logging and enhance error reporting
  cmd/apply.go
  cmd/root.go
  go.mod
  go.sum
Labels: enhancement, minor
