Repository k1LoW/deck, pull requests merged in 2025-07, with the labels that each got.

#179 fix: check sum comparison of images
  slide.go
Labels: bug

#181 fix: add CODEBLOCK_CONTENT env to cmd
  md/md.go
Labels: bug

#188 feat: support dynamic heading levels for title detection
  README.md
  md/md.go
  md/md_test.go
  testdata/heading.md
  testdata/heading.md.golden
Labels: enhancement, minor

#204 feat: Add {{output}} template variable support for code-block-to-image-command
  README.md
  md/md.go
  md/md_test.go
  md/testdata/stub_code_img.go
Labels: enhancement, minor

#206 feat(md): add support for block quotes
  md/md.go
  md/md_test.go
  slide.go
  testdata/blockquote.md
  testdata/blockquote.md.golden
Labels: breaking change

#213 feat: Add ignore page functionality with page configuration comment
  README.md
  md/md.go
  md/md_test.go
  testdata/ignore.md
  testdata/ignore.md.golden
Labels: enhancement, minor

#227 perf: add debounce function to avoid busy loop while watching
  cmd/apply.go
Labels: enhancement, minor

#208 feat: support block quotes
  README.md
  action.go
  deck.go
  integration_test.go
  md/md.go
  testdata/blockquote.md-1.golden.png
  testdata/blockquote.md-2.golden.png
Labels: enhancement, minor

#238 fix(compare): move comparison logic to a new file and simplify equality check
  action.go
  compare.go
  deck.go
  integration_apply_test.go
  integration_test.go
Labels: bug, enhancement

#239 feat(deck): add affine transform for images and block quotes
  deck.go
  go.mod
  go.sum
  integration_action_test.go
  integration_apply_test.go
  integration_test.go
  testdata/blockquote.md-2.golden.png
  testdata/images.md-2.golden.png
Labels: enhancement, breaking change

#244 fix(md): resolve concurrency issue in code block image generation
  md/md.go
  testdata/codeblock.md-1.golden.png
Labels: bug

#253 fix: does not copy images/shapes from markdown when update layout
  deck.go
Labels: bug

#254 feat: Add breaks frontmatter option to control line break rendering
  README.md
  integration_test.go
  md/md.go
  md/md_test.go
  testdata/breaks_default.md
  testdata/breaks_default.md-1.golden.png
  testdata/breaks_default.md-2.golden.png
  testdata/breaks_default.md-3.golden.png
  testdata/breaks_default.md.golden
  testdata/breaks_enabled.md
  testdata/breaks_enabled.md-1.golden.png
  testdata/breaks_enabled.md-2.golden.png
  testdata/breaks_enabled.md-3.golden.png
  testdata/breaks_enabled.md.golden
Labels: enhancement, minor

#256 chore: Merge UpdateTextStyleRequest into one
  deck.go
Labels: enhancement

#225 feat: HTML element styling feature
  README.md
  action_test.go
  compare.go
  deck.go
  integration_action_test.go
  integration_test.go
  md/md.go
  md/md_test.go
  slide.go
  testdata/html_element_style.md
  testdata/html_element_style.md.golden
  testdata/style.md.golden
Labels: enhancement, minor

#261 fix: proper inline styling in lists
  deck.go
  testdata/nested_list.md
  testdata/nested_list.md-5.golden.png
  testdata/nested_list.md.golden
Labels: bug

#267 fix: improve split markdown as contents
  md/md.go
  md/md_test.go
  testdata/codeblock.md
  testdata/codeblock.md-1.golden.png
  testdata/codeblock.md-2.golden.png
  testdata/codeblock.md.golden
Labels: bug

#266 fix case of presentationID
  cmd/new.go
  md/frontmatter.go
  md/frontmatter_test.go
Labels: bug

#276 fix(compare): ensure images are sorted without modifying input slices
  compare.go
Labels: bug

#272 fix: support for different number of images and placeholders / use replace image api
  deck.go
  testdata/images.md
  testdata/images.md-2.golden.png
  testdata/images.md-3.golden.png
  testdata/images.md.golden
Labels: breaking change

#273 feat: apply inline styles to headings
  action_test.go
  deck.go
  integration_action_test.go
  integration_apply_test.go
  integration_test.go
  md/md.go
  slide.go
  testdata/code.md-1.golden.png
  testdata/code.md.golden
  testdata/codeblock.md-1.golden.png
Labels: enhancement, minor

#285 fix: apply
  Makefile
  testdata/codeblock.md-1.golden.png
Labels: bug

#291 fix(md): handle nil Frontmatter in ToSlides method
  md/md.go
Labels: bug

#293 feat: support `skip` `ignore` `freeze` for `defaults:`
  README.md
  md/md.go
  testdata/defaults.md
  testdata/ignore.md.golden
Labels: enhancement, breaking change

#297 feat: add support for user profiles in deck operations
  README.md
  client.go
  cmd/apply.go
  cmd/export.go
  cmd/ls.go
  cmd/lsLayouts.go
  cmd/new.go
  cmd/root.go
  deck.go
  list.go
Labels: enhancement, minor

#300 feat: add 'open' subcommand to open Google Slides in browser
  README.md
  cmd/open.go
  list.go
Labels: enhancement, minor

#307 perf: Batch delete pages
  apply.go
  deck.go
  integration_action_test.go
  logger/dot/dot.go
Labels: enhancement

#312 feat: Add default definitions for HTML inline styles
  apply.go
  style.go
  testdata/style.md
  testdata/style.md-2.golden.png
  testdata/style.md.golden
Labels: enhancement, minor

#317 feat: adjust imageReplaceMethod for code blocks
  action.go
  apply.go
  md/md.go
  slide.go
Labels: enhancement, minor
